const path = require("path");

module.exports = {
  publicPath: "/static/clinic/vue/dist", // Should be STATIC_URL + path/to/build
  // publicPath: "/", // Should be STATIC_URL + path/to/build
  // outputDir: path.resolve(__dirname, "../static/clinic/vue/dist/"), // Output to a directory in
  outputDir: path.resolve(__dirname, "../static/clinic/vue/dist/"), // Output to a directory in STATICFILES_DIRS
  assetsDir: "", //A directory (relative to outputDir) to nest generated static assets (js, css, img, fonts) under.

  filenameHashing: false, // Django will hash file names, not webpack. By default, generated static assets contains hashes in their filenames for better caching control. However, this requires the index HTML to be auto-generated by Vue CLI. If you cannot make use of the index HTML generated by Vue CLI, you can disable filename hashing by setting this option to false
  runtimeCompiler: true, // See: https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only
  devServer: {
    writeToDisk: true, // Write files to disk in dev mode, so Django can serve the assets
  },
};
