# Generated by Django 3.2.3 on 2021-05-31 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('short_link', models.CharField(max_length=15, unique=True)),
                ('long_link', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlinks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
