# Generated by Django 3.2.3 on 2021-06-05 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0002_alter_shortlink_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlinks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
